### ISSUE TITLE
Error after exploding dynamite

### ISSUE THREAD

**Issue by Nexus9w9** [boymelancholy/DropItem3D#4]
-> This happened after I exploded hundreds of dynamites, I would like to know if it is a limitation or a bug of your plugin.

[00:50:50.975] [Server thread/CRITICAL]: LogicException: "Cannot schedule update on garbage entity pocketmine\entity\object\ItemEntity" (EXCEPTION) in "pmsrc/src/entity/Entity" at line 1000
--- Stack trace ---
  #0 pmsrc/src/entity/Entity(1535): pocketmine\entity\Entity->scheduleUpdate()
  #1 plugins/DropItem3D-73cfea422e30e3ec61bcdbf70af0ef048b00077a/src/boymelancholy/di3d/listener/drop/DropItemListener(47): pocketmine\entity\Entity->flagForDespawn()
  #2 pmsrc/src/scheduler/ClosureTask(63): boymelancholy\di3d\listener\drop\DropItemListener->boymelancholy\di3d\listener\drop\{closure}()
  #3 pmsrc/src/scheduler/TaskHandler(117): pocketmine\scheduler\ClosureTask->onRun()
  #4 pmsrc/src/scheduler/TaskScheduler(144): pocketmine\scheduler\TaskHandler->run()
  #5 pmsrc/src/plugin/PluginManager(478): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 1616)
  #6 pmsrc/src/Server(1769): pocketmine\plugin\PluginManager->tickSchedulers(integer 1616)
  #7 pmsrc/src/Server(1658): pocketmine\Server->tick()
  #8 pmsrc/src/Server(1047): pocketmine\Server->tickProcessor()
  #9 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[41] C:\Users\Allyson\Documents\R. Futuristic\, string[49] C:\Users\Allyson\Documents\R. Futuristic\plugins\)
  #10 pmsrc/src/PocketMine(327): pocketmine\server()
  #11 pmsrc(11): require(string[85] phar://C:/Users/Allyson/Documents/R. Futuristic/PocketMine-MP.phar/src/PocketMin)
--- End of exception information ---
[00:50:50.981] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[00:50:51.038] [Server thread/EMERGENCY]: Please upload the "C:/Users/Allyson/Documents/R. Futuristic/crashdumps/Thu_May_12-10.50.50-+07_2022.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[00:50:51.047] [Server thread/EMERGENCY]: Forcing server shutdown

**Comment by boymelancholy** [comment]
Thanks for reporting.
Fixing it later.

**Comment by boymelancholy** [comment]
This plugin is pre-release now.
I struggle to find bugs :(

**Comment by boymelancholy** [comment]
A few minutes ago I have tested to explode 1k amount of TNT.
But, the error has not occurred.

**Comment by Nexus9w9** [comment]
> A few minutes ago I have tested to explode 1k amount of TNT.
> But, the error has not occurred.

I think it was because I was exploding the blocks of land and that generated the error

**Comment by boymelancholy** [comment]
Hmm...
Tbh, that's lack of info.
So I'll put it off.

**Comment by Nexus9w9** [comment]
> Hmm...
> Tbh, that's lack of info.
> So I'll put it off.

like this?

**Comment by boymelancholy** [comment]
I don't have sufficient knowledges about generator.
So I'll put it off fixing.
