### ISSUE TITLE
Netherite items wanna behave like vanilla.

### ISSUE THREAD

**Issue by xodamcm** [boymelancholy/DropItem3D#6]
Item3D aren’t affected by lava, lava doesn’t kill items

**Comment by xodamcm** [comment]
Perfect, thank's !! It's possible to put: Netherite Items doesn't burn (not flaggedfordespawn on lava, like in Vanilla)

**Comment by boymelancholy** [comment]
Ok, add the features later

**Comment by xodamcm** [comment]
Thx !!

**Comment by boymelancholy** [comment]
I have not known Netherite items does not burn just now.
The last time I played minecraft in vanilla was around 1.14.0 lol.

**Comment by xodamcm** [comment]
Oh okok, I am also a former player, I do not know all the news, but this one is part of the one I know, anyway thank you for your work !!

**Comment by boymelancholy** [comment]
Updated in c5f11b1d9fb38dae1d4e9f3a369c29a3bdcf1c88
But, pmmp/PocketMine-MP has not implemented Netherite items yet.
So I cannot debug about it.
