### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by logannn61** [boymelancholy/DropItem3D#8]
**Bug overview**
The server crashes
https://crash.pmmp.io/view/6915460

**Process to bug outbreak**
I don’t know I was not online

**Expected behavior**
Not to crash

**Your environment**
 - OS: Linux
 - Version: latest 
 - PMMP Version: Server version: 4.3.4 (git hash: xxxxxx)

**Comment by boymelancholy** [comment]
"I don’t know I was not online"

**Comment by boymelancholy** [comment]
This error source handle is `ColinHDev\VanillaHopper\entities\ItemEntity`.
DropItem3D has the feature to delete item entity when it lands.
Probably, this error caused by it.

For now, we will ignore this issue as it does not detract from the functionality of DropItem3D.
